algo_1h_btc:
  BTC_1H_API_KEY: v1BVNWILKxBjhKcAll
  BTC_1H_SECRET_KEY: 4elM1o90rCuUOzAskTZ1D9ZWUNNaa70E3JIz

algo_1h_eth:
  ETH_1H_API_KEY: 1wJtWMgUAWu97q6uoQ
  ETH_1H_SECRET_KEY: 8jpl4ghGRvNAPsuYgtxWFiDkgTY49J17UVOF

algo_1h_sol:
  SOL_1H_API_KEY: xE6Kqj6BzvAjlxomM0
  SOL_1H_SECRET_KEY: jJap2F5USqczoMxEXRmIjbDdKxD891TIR8Lz

algo_1h_sui:
  SUI_1H_API_KEY: 81YHmxte2OMOIfSq0a
  SUI_1H_SECRET_KEY: LMLXP7buO2OjPGP92a0zmmwWjpxTB5LSkY8c

algo_1h_doge:
  DOGE_1H_API_KEY: nwlYq93vSaCMIzBac0
  DOGE_1H_SECRET_KEY: F5xRYEYfvarGQ6d2Tas5r7mhBgYBYvdG6lak

grassnode:
  GN_API: 2wlOd0ApVQgg4SDPqFk2Lq2Btku

tg_bot:
  TOKEN: 8198276230:AAETb0a9FMrRBd1IGn3XtiWFfOuwHVpgf3Y
  GROUP_ID: 8394621040